# Site settings
theme: jekyll-theme-easy-wedding
title: Andrew and Blue are Getting Married
email: chang.andrew.23+wedding@gmail.com
url: "https://www.andrewandbluearegettingmarried.rsvp"
description: "We're getting married"
baseurl: ""
context: "chi"

collections:
  stories:
    sort_by: order
  banners:

sass:
  style: compressed

defaults:
  - scope:
      path: "photos/"
    values:
      image: true
  - scope:
      type: banners
    values:
      layout: banner

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - _compress_images_cache.yml
